import React, { useState, useEffect } from 'react';
import { ShieldCheck, Calendar, Clock, Car, Info, CheckCircle2, Save, MapPin } from 'lucide-react';

export function FieldObservationPage() {
  const [observations, setObservations] = useState([]);
  
  // Form State
  const [formData, setFormData] = useState({
    location: '',
    observation_date: '',
    start_time: '',
    end_time: '',
    duration_minutes: '',
    total_vehicles: '',
    cars: '',
    motorcycles: '',
    buses: '',
    trucks: '',
    max_queue_length: '',
    average_waiting_time: '',
    peak_period: '',
    notes: '',
    observer: ''
  });

  useEffect(() => {
    // Load from local storage
    const saved = localStorage.getItem('field_observations');
    if (saved) {
      setObservations(JSON.parse(saved));
    }
  }, []);

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSave = (e) => {
    e.preventDefault();
    
    // Validation
    if (Number(formData.duration_minutes) <= 0) {
      alert("Duration must be greater than 0."); return;
    }
    if (Number(formData.total_vehicles) < 0 || Number(formData.cars) < 0 || Number(formData.motorcycles) < 0 || Number(formData.buses) < 0 || Number(formData.trucks) < 0) {
      alert("Vehicle counts cannot be negative."); return;
    }
    if (Number(formData.max_queue_length) < 0 || Number(formData.average_waiting_time) < 0) {
      alert("Queue length and waiting time cannot be negative."); return;
    }
    
    const newObs = {
      ...formData,
      id: Date.now(),
      verified: true
    };
    const updated = [newObs, ...observations];
    setObservations(updated);
    localStorage.setItem('field_observations', JSON.stringify(updated));
    setFormData({
      location: '',
      observation_date: '',
      start_time: '',
      end_time: '',
      duration_minutes: '',
      total_vehicles: '',
      cars: '',
      motorcycles: '',
      buses: '',
      trucks: '',
      max_queue_length: '',
      average_waiting_time: '',
      peak_period: '',
      notes: '',
      observer: ''
    });
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '26px' }}>
      <div className="glass-card" style={{ padding: '24px 28px', border: '1px solid var(--border-subtle)' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 800, color: 'var(--text-main)', marginBottom: '8px' }}>
          Field Observations
        </h1>
        <p style={{ color: 'var(--text-muted)', fontSize: '14px', margin: 0 }}>
          Manual traffic observations recorded at the college gates for AI validation.
        </p>
        <div style={{ marginTop: '16px', padding: '12px', background: 'var(--emerald-bg)', border: '1px solid var(--emerald-border)', borderRadius: '8px', color: 'var(--emerald-400)', fontSize: '13px', display: 'flex', gap: '8px' }}>
          <Info size={16} />
          <span>Enter only values collected during physical field observation. These values are not generated by AI. Do not use fake placeholder values.</span>
        </div>
      </div>

      <div className="glass-card" style={{ padding: '24px', border: '1px solid var(--border-subtle)' }}>
        <h3 style={{ fontSize: '18px', fontWeight: 700, color: 'var(--text-main)', marginBottom: '16px' }}>
          Add New Observation
        </h3>
        <form onSubmit={handleSave} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px' }}>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Gate Location</label>
            <input type="text" name="location" value={formData.location} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Observation Date</label>
            <input type="date" name="observation_date" value={formData.observation_date} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Start Time</label>
            <input type="time" name="start_time" value={formData.start_time} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>End Time</label>
            <input type="time" name="end_time" value={formData.end_time} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Duration (minutes)</label>
            <input type="number" name="duration_minutes" value={formData.duration_minutes} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Total Vehicles</label>
            <input type="number" name="total_vehicles" value={formData.total_vehicles} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Cars</label>
            <input type="number" name="cars" value={formData.cars} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} />
          </div>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Motorcycles</label>
            <input type="number" name="motorcycles" value={formData.motorcycles} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} />
          </div>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Buses</label>
            <input type="number" name="buses" value={formData.buses} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} />
          </div>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Trucks</label>
            <input type="number" name="trucks" value={formData.trucks} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Max Queue Length</label>
            <input type="number" name="max_queue_length" value={formData.max_queue_length} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Avg Waiting Time (mins)</label>
            <input type="number" name="average_waiting_time" value={formData.average_waiting_time} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Peak Time</label>
            <input type="time" name="peak_period" value={formData.peak_period} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>
          
          <div>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Observer Name</label>
            <input type="text" name="observer" value={formData.observer} onChange={handleChange} style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }} required />
          </div>

          <div style={{ gridColumn: '1 / -1' }}>
            <label style={{ display: 'block', fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '4px' }}>Notes</label>
            <textarea name="notes" value={formData.notes} onChange={handleChange} rows="2" style={{ width: '100%', padding: '8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', background: 'var(--bg-card)' }}></textarea>
          </div>

          <div style={{ gridColumn: '1 / -1', display: 'flex', justifyContent: 'flex-end' }}>
            <button type="submit" style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 16px', background: 'var(--accent)', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 600 }}>
              <Save size={16} /> Save Observation
            </button>
          </div>
        </form>
      </div>

      <div style={{ width: '100%', overflowX: 'auto' }}>
        <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse', fontSize: '14px', background: 'var(--bg-card)', borderRadius: '8px', overflow: 'hidden' }}>
          <thead>
            <tr style={{ background: 'var(--bg-card-hover)', borderBottom: '1px solid var(--border-subtle)' }}>
              <th style={{ padding: '12px' }}>Date</th>
              <th style={{ padding: '12px' }}>Duration</th>
              <th style={{ padding: '12px' }}>Peak Time</th>
              <th style={{ padding: '12px' }}>Total Vehicles</th>
              <th style={{ padding: '12px' }}>Max Queue</th>
              <th style={{ padding: '12px' }}>Avg Waiting Time</th>
              <th style={{ padding: '12px' }}>Source</th>
            </tr>
          </thead>
          <tbody>
            {observations.length === 0 ? (
              <tr>
                <td colSpan="7" style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)' }}>
                  No observations recorded yet.
                </td>
              </tr>
            ) : (
              observations.map((obs) => (
                <tr key={obs.id} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                  <td style={{ padding: '12px' }}>{obs.observation_date}</td>
                  <td style={{ padding: '12px' }}>{obs.duration_minutes}m</td>
                  <td style={{ padding: '12px' }}>{obs.peak_period}</td>
                  <td style={{ padding: '12px' }}>{obs.total_vehicles}</td>
                  <td style={{ padding: '12px' }}>{obs.max_queue_length}</td>
                  <td style={{ padding: '12px' }}>{obs.average_waiting_time}m</td>
                  <td style={{ padding: '12px' }}>
                    <span style={{ fontSize: '11px', padding: '4px 8px', background: 'var(--emerald-bg)', color: 'var(--emerald-400)', borderRadius: '4px', fontWeight: 600 }}>REAL FIELD DATA</span>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
