import React from 'react';
import { Sparkles } from 'lucide-react';

export function DemoBadge({ text = 'DEMO / SIMULATED DATA', className = '', size = 'sm' }) {
  const isXs = size === 'xs';
  return (
    <span
      className={`inline-flex items-center gap-1 font-mono font-medium rounded-full ${
        isXs ? 'px-2 py-0.5 text-[10px]' : 'px-2.5 py-1 text-xs'
      } bg-purple-500/10 text-purple-300 border border-purple-500/30 ${className}`}
      title="This metric is generated by the AI demo simulation engine."
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        padding: isXs ? '2px 6px' : '3px 8px',
        borderRadius: '999px',
        fontSize: isXs ? '10px' : '11px',
        fontWeight: 600,
        backgroundColor: 'rgba(139, 92, 246, 0.15)',
        color: '#c084fc',
        border: '1px solid rgba(139, 92, 246, 0.35)',
        letterSpacing: '0.03em',
        textTransform: 'uppercase'
      }}
    >
      <Sparkles size={isXs ? 10 : 12} className="text-purple-400" />
      {text}
    </span>
  );
}
